import { parseStreamingJson } from '@earendil-works/pi-ai';
import {
  AssistantMessageComponent, BashExecutionComponent, BranchSummaryMessageComponent,
  CompactionSummaryMessageComponent, CustomMessageComponent, SkillInvocationMessageComponent,
  ToolExecutionComponent, UserMessageComponent, getMarkdownTheme, parseSkillBlock,
  createBashToolDefinition, createEditToolDefinition, createFindToolDefinition,
  createGrepToolDefinition, createLsToolDefinition, createPowerShellToolDefinition,
  createReadToolDefinition, createWriteToolDefinition,
  type ToolRenderers, type TruncationResult,
} from '@earendil-works/pi-coding-agent';
import { Container, Spacer, Text, type Component, type TUI } from '@earendil-works/pi-tui';
import { WidthCache } from './width-cache.js';
import type { PresentationHost } from './presentation.js';
import type { RecordValue } from './protocol.js';
import { messageKey, RemoteView, safeText, transcriptMessages } from './view.js';

/** Strip wire-supplied terminal controls, not the ANSI generated by trusted Pi components. */
function displayValue<T>(value: T): T {
  if (typeof value === 'string') return safeText(value) as T;
  if (Array.isArray(value)) return value.map(displayValue) as T;
  if (value && typeof value === 'object') return Object.fromEntries(
    Object.entries(value).map(([key, item]) => [safeText(key), displayValue(item)]),
  ) as T;
  return value;
}

/** Public tool factories supply rendering fields only. No executor is retained or invoked. */
export function builtinToolRenderers(cwd: string): Map<string, ToolRenderers> {
  const renderers = new Map<string, ToolRenderers>();
  for (const factory of [createReadToolDefinition, createBashToolDefinition, createEditToolDefinition,
    createWriteToolDefinition, createGrepToolDefinition, createFindToolDefinition, createLsToolDefinition,
    createPowerShellToolDefinition]) {
    const { name, renderCall, renderResult, renderShell } = factory(cwd) as ToolRenderers & { name: string };
    renderers.set(name, { renderCall, renderResult, renderShell });
  }
  const edit = renderers.get('edit')!;
  const renderEditCall = edit.renderCall!;
  // Pi's edit renderer previews a complete call by reading context.cwd. That is a REMOTE
  // path here. Suppress only that local preview; renderResult still uses the remote diff.
  edit.renderCall = (args, theme, context) => renderEditCall(args, theme, { ...context, argsComplete: false });
  return renderers;
}

const EMPTY_TOOL_ARGS: RecordValue = Object.freeze({});
interface ParsedToolArgs { text: string; args: RecordValue }

interface ToolState {
  name: string; args: RecordValue; argsComplete?: boolean; executionStarted?: boolean;
  result?: RecordValue; isPartial?: boolean; isError?: boolean; failure?: string;
}
interface ToolRow {
  component: ToolExecutionComponent; name: string; args: unknown; result?: RecordValue;
  argsComplete?: boolean; executionStarted?: boolean; expanded?: boolean; isPartial?: boolean; isError?: boolean;
}

/**
 * Display-only composition of public Pi components. Pi owns Markdown, colors, padding,
 * tool shells, renderer state and expansion. The remote client owns wire reconciliation.
 */
export class Transcript extends Container {
  expanded = false;
  thinking = true;
  readonly notices: string[] = [];
  private dirty = true;
  private host?: PresentationHost;
  private cwd?: string;
  private session?: string;
  private rendererRevision?: number;
  private hiddenThinkingLabel?: string;
  private defaults = new Map<string, ToolRenderers>();
  private tools = new Map<string, ToolRow>();
  private parsedToolArgs = new WeakMap<RecordValue, ParsedToolArgs>();
  private derivedMessages = new WeakMap<RecordValue, RecordValue>();
  private messages = new Map<string, { source: RecordValue; component: Component }>();
  private renderedExpanded = this.expanded;
  private renderedThinking = this.thinking;
  private readonly widthCache = new WidthCache();

  constructor(private view: RemoteView, private ui: TUI,
    private presentation: () => PresentationHost | undefined = () => undefined) { super(); }

  changed(): void { this.dirty = true; }
  override invalidate(): void { super.invalidate(); this.changed(); }
  notify(message: string): void {
    this.notices.push(safeText(message));
    if (this.notices.length > 50) this.notices.shift();
    this.changed();
  }
  /** Drop per-call renderer state when switching sessions, reconnecting, or reloading UI. */
  reset(): void {
    for (const row of this.tools.values()) this.retire(row);
    this.host?.retainToolCalls([]);
    this.tools.clear(); this.parsedToolArgs = new WeakMap(); this.derivedMessages = new WeakMap();
    this.messages.clear(); this.widthCache.clear(); this.changed();
  }

  private retire(row: ToolRow): void {
    if (row.isPartial === false) return;
    // Native shell renderers have no dispose method: their public final-result path
    // stops the elapsed-time timer. Retire while the host is still active, before
    // dropping the component. This does not alter remote state or persisted messages.
    const result = displayValue(row.result ?? { content: [] });
    row.component.updateResult({ ...result, content: result.content ?? [], isError: !!row.isError }, false);
    row.isPartial = false;
  }

  private tool(id: string, state: ToolState): ToolExecutionComponent {
    let row = this.tools.get(id);
    if (!row || row.name !== state.name) {
      if (row) this.retire(row);
      const fallback = this.defaults.get(state.name);
      const renderers = this.host ? this.host.toolRenderers(state.name, fallback) : fallback;
      const component = new ToolExecutionComponent(safeText(state.name), id, displayValue(state.args),
        { showImages: false }, renderers, this.ui, this.cwd!);
      row = { component, name: state.name, args: state.args };
      this.tools.set(id, row);
    }
    const component = row.component;
    if (row.args !== state.args) { component.updateArgs(displayValue(state.args)); row.args = state.args; }
    if (state.argsComplete && !row.argsComplete) { component.setArgsComplete(); row.argsComplete = true; }
    if (state.executionStarted && !row.executionStarted) { component.markExecutionStarted(); row.executionStarted = true; }
    if (state.result && (row.result !== state.result || row.isPartial !== state.isPartial || row.isError !== state.isError)) {
      component.updateResult({ ...displayValue(state.result), content: displayValue(state.result.content ?? []), isError: !!state.isError }, !!state.isPartial);
      row.result = state.result; row.isPartial = state.isPartial; row.isError = state.isError;
    }
    if (row.expanded !== this.expanded) { component.setExpanded(this.expanded); row.expanded = this.expanded; }
    return component;
  }

  private message(source: RecordValue): Component {
    const key = messageKey(source);
    const cached = this.messages.get(key);
    if (cached?.source === source) return cached.component;
    const message = displayValue(source);
    const container = new Container();
    const markdownTheme = getMarkdownTheme();
    const transformers = this.host?.markdownTransformers ?? [];
    switch (message.role) {
      case 'user': {
        const text = typeof message.content === 'string' ? message.content : (message.content ?? [])
          .filter((block: RecordValue) => block?.type === 'text').map((block: RecordValue) => block.text).join('');
        if (!text) break;
        const skill = parseSkillBlock(text);
        if (skill) {
          const component = new SkillInvocationMessageComponent(skill, markdownTheme);
          component.setExpanded(this.expanded); container.addChild(component);
          if (skill.userMessage) { container.addChild(new Spacer(1)); container.addChild(new UserMessageComponent(skill.userMessage, markdownTheme, 1, transformers)); }
        } else container.addChild(new UserMessageComponent(text, markdownTheme, 1, transformers));
        break;
      }
      case 'assistant': {
        message.content = Array.isArray(message.content) ? message.content.filter(Boolean) : [];
        const component = new AssistantMessageComponent(undefined, !this.thinking, markdownTheme, this.host?.hiddenThinkingLabel, 1, transformers);
        component.updateContent(message as Parameters<AssistantMessageComponent['updateContent']>[0], message.stopReason === 'pending');
        container.addChild(component); break;
      }
      case 'custom': {
        if (message.display === false) break;
        const component = new CustomMessageComponent(message as ConstructorParameters<typeof CustomMessageComponent>[0],
          this.host?.messageRenderer(message.customType), markdownTheme, 1);
        component.setExpanded(this.expanded); container.addChild(component); break;
      }
      case 'entry': {
        // Custom entries are extension state, not visible messages without a renderer.
        const component = this.host?.renderEntry(message, { expanded: this.expanded });
        if (component) { container.addChild(new Spacer(1)); container.addChild(component); }
        break;
      }
      case 'bashExecution': {
        const component = new BashExecutionComponent(message.command, this.ui, message.excludeFromContext);
        // Complete immediately to stop the component's running-loader timer.
        component.setComplete(message.exitCode, !!message.cancelled,
          message.truncated ? { truncated: true } as TruncationResult : undefined, message.fullOutputPath);
        if (message.output) component.appendOutput(message.output);
        component.setExpanded(this.expanded); container.addChild(component); break;
      }
      case 'compactionSummary': case 'branchSummary': {
        const component = message.role === 'compactionSummary'
          ? new CompactionSummaryMessageComponent(message as ConstructorParameters<typeof CompactionSummaryMessageComponent>[0], markdownTheme)
          : new BranchSummaryMessageComponent(message as ConstructorParameters<typeof BranchSummaryMessageComponent>[0], markdownTheme);
        component.setExpanded(this.expanded); container.addChild(new Spacer(1)); container.addChild(component); break;
      }
    }
    this.messages.set(key, { source, component: container });
    return container;
  }

  private toolArgs(block: RecordValue): RecordValue {
    if (!block.argumentText) return block.arguments ?? EMPTY_TOOL_ARGS;
    // RemoteView preserves unchanged blocks across assistant-text deltas. Parsing each rebuild
    // would produce new args identities and needlessly recreate historical renderer components.
    // Track text too: mutable test fixtures can update a block without replacing its identity.
    const cached = this.parsedToolArgs.get(block);
    if (cached && cached.text === block.argumentText) return cached.args;
    const args = parseStreamingJson(block.argumentText);
    this.parsedToolArgs.set(block, { text: block.argumentText, args });
    return args;
  }

  private rebuild(): void {
    this.clear();
    const messages = transcriptMessages(this.view.snapshot, this.derivedMessages);
    const tools = new Map<string, ToolState>();
    for (const message of messages) if (message.role === 'assistant') {
      for (const block of Array.isArray(message.content) ? message.content : []) {
        if (block?.type !== 'toolCall' || !block.id) continue;
        const failed = message.stopReason === 'aborted' || message.stopReason === 'error';
        tools.set(block.id, { name: block.name,
          args: this.toolArgs(block),
          argsComplete: message.stopReason !== 'pending',
          failure: failed ? (message.stopReason === 'aborted' ? 'Operation aborted' : message.errorMessage || 'Error') : undefined,
        });
      }
    }
    for (const live of Object.values(this.view.snapshot.live.tools)) {
      // Nested executions are rendered inside their parent, not again at transcript level.
      if (live.parentToolCallId) continue;
      tools.set(live.toolCallId, { ...tools.get(live.toolCallId), name: live.toolName,
        args: live.args ?? tools.get(live.toolCallId)?.args ?? EMPTY_TOOL_ARGS, result: live.result ?? live.partialResult,
        isPartial: live.type !== 'tool_execution_end', isError: !!live.isError, executionStarted: true, argsComplete: true });
    }
    for (const message of messages) if (message.role === 'toolResult') tools.set(message.toolCallId, {
      ...tools.get(message.toolCallId), name: message.toolName, args: tools.get(message.toolCallId)?.args ?? EMPTY_TOOL_ARGS,
      result: message, isPartial: false, isError: !!message.isError, argsComplete: true,
    });
    for (const tool of tools.values()) if (tool.failure && (!tool.result || tool.isPartial)) {
      tool.result = { content: [{ type: 'text', text: tool.failure }] }; tool.isError = true; tool.isPartial = false;
    }
    for (const [id, row] of this.tools) if (!tools.has(id)) { this.retire(row); this.tools.delete(id); }
    this.host?.retainToolCalls(tools.keys());
    const used = new Set<string>();
    const appendTool = (id: string) => {
      if (used.has(id)) return;
      const state = tools.get(id);
      if (state) { used.add(id); this.addChild(this.tool(id, state)); }
    };
    if (this.host?.header) this.addChild(this.host.header);
    let hasContent = false;
    const keys = new Set<string>();
    for (const message of messages) {
      keys.add(messageKey(message));
      if (message.role === 'toolResult') { appendTool(message.toolCallId); continue; }
      if (message.role === 'system') continue;
      const component = this.message(message);
      // Empty/image-only users and hidden entries add no transcript spacing.
      if (!(component as Container).children.length) continue;
      if (message.role === 'user' && hasContent) this.addChild(new Spacer(1));
      this.addChild(component);
      hasContent = true;
      if (message.role === 'assistant') for (const block of Array.isArray(message.content) ? message.content : []) {
        if (block?.type === 'toolCall') appendTool(block.id);
      }
    }
    for (const key of this.messages.keys()) if (!keys.has(key)) this.messages.delete(key);
    for (const id of tools.keys()) appendTool(id);
    // Older RPC snapshots supply output but not a shell command until completion.
    for (const shell of Object.values(this.view.snapshot.live.bash ?? {})) {
      this.addChild(new Spacer(1)); this.addChild(new Text(`Remote shell\n${safeText(shell.output)}`, 1, 0));
    }
    for (const notice of this.notices) this.addChild(new Text(notice, 1, 0));
    this.dirty = false;
  }

  override render(width: number): string[] {
    const host = this.presentation();
    const cwd = this.view.snapshot.slot.cwd;
    const session = this.view.snapshot.state.sessionFile ?? this.view.snapshot.state.sessionId;
    if (host !== this.host || cwd !== this.cwd || session !== this.session || host?.rendererRevision !== this.rendererRevision) {
      this.reset();
      this.host = host; this.cwd = cwd; this.session = session; this.rendererRevision = host?.rendererRevision;
      this.defaults = builtinToolRenderers(cwd);
    }
    if (this.renderedExpanded !== this.expanded || this.renderedThinking !== this.thinking || this.hiddenThinkingLabel !== host?.hiddenThinkingLabel) {
      this.renderedExpanded = this.expanded; this.renderedThinking = this.thinking; this.hiddenThinkingLabel = host?.hiddenThinkingLabel;
      this.messages.clear(); this.changed();
    }
    if (this.dirty) this.rebuild();
    // Pi components own normal layout; enforce the client width contract even at 1 column.
    return this.widthCache.clamp(super.render(width), width);
  }
}
